### ISSUE TITLE
Could you send me fully source code of this repo?

### ISSUE THREAD

**Issue by TanPhuNguyen** [Anki0909/BreakHist-Dataset-Image-Classification#1]

**Comment by TanPhuNguyen** [comment]
I really need to know training and testing process in classifying depend on the magnification of breast cancer.

**Comment by Anki0909** [comment]
You can find the rough version of my code on [kaggle](https://www.kaggle.com/ankur1809/breakhist-dataset/kernels). Will try to upload clean version of my code here soon
