### ISSUE TITLE
Could you send me your BreakHist-Dataset ?

### ISSUE THREAD

**Issue by nightfuryyy** [Anki0909/BreakHist-Dataset-Image-Classification#2]
i found this link "https://web.inf.ufpr.br/vri/databases/breast-cancer-histopathological-database-breakhis/" but its not same structure as your dataset . I tried to change file data_processing.py but it not work. "IndexError: unsupported iterator index" at " 12     labels_one_hot.flat[index_offset + labels_dense.ravel()] = 1" .

**Comment by Anki0909** [comment]
@nightfuryyy you can refer to this [link](https://www.kaggle.com/ankur1809/breakhist-dataset) for dataset, I have initially tried it on kaggle kernel and than posted it here. The code here is messed up to be honest, I will try to upload a cleaner version soon

**Comment by nightfuryyy** [comment]
thanks, but I successfully fixed it :P

**Comment by Anki0909** [comment]
sorry for late reply

**Comment by nightfuryyy** [comment]
thank u so much for the source

Vào Th 2, 20 thg 5, 2019 vào lúc 15:05 Ankur Satpute <
notifications@github.com> đã viết:

**Comment by Teslakgp** [comment]
"IndexError: unsupported iterator index" at " 12 labels_one_hot.flat[index_offset + labels_dense.ravel()] = 1" . 
How to fix this error???
https://www.kaggle.com/ankur1809/breakhist-dataset
I am using the above dataset

**Comment by Anki0909** [comment]
@Teslakgp you can use any one hot encoding function in place of that function, that's all that function is doing. Anyways this is very old and outdated code TBH. Just follow Keras documentation for up-to-date stuff. Or let me know if you want me to revamped all this thing myself

**Comment by Teslakgp** [comment]
Can you please revamp it?

**Comment by Teslakgp** [comment]
@Anki0909 I tried but couldn't do successfully it will be great if you do the change.

**Comment by SyedSaba** [comment]
Hi Ankur Satpute 
I had found your work and it's really appreciating 
But I couldn't find the dataset here, thus I downloaded the BreaKHis dataset from the following link (https://web.inf.ufpr.br/vri/databases/breast-cancer-histopathological-database-breakhis/), but I'm facing some errors. After understanding your code, I think you followed different dataset directories according to my knowledge.
I will be thankful to you if you share the dataset 

Thanks
